### PR TITLE
fixed overall font sizes; fixed author linking

### PR DESCRIPTION
**Pull request by coallaoh**

### CODE REVIEW

**Review by ElisaNguyen — COMMENTED** [review]
The font sizes are smaller than before and it looks better, but now that I paid attention to it, I think it would look better if the font size of the menu (top right) is not smaller than the text font size. Author linking works!

Minor: Remove space after each author and the following comma. Maybe also limit size of image in a publication page and center it?

**Review by arubique — APPROVED** [review]
Font changes are difficult for me to notice but the website still looks nice which is good!

**Comment by coallaoh** [comment]
@ElisaNguyen The font size for the top-right menu is 18 px and the text font size is also 18 px at the moment. Do you think it makes sense to increase the font size for top-right menu?

**Comment by ElisaNguyen** [comment]
@coallaoh If it is the same size I think it is fine. Somehow it showed up slightly larger before on my screen!

**Comment by coallaoh** [comment]
- Fixed weird space after commas in authors
- Removed publication pages -- if you wish to write something special or make a project web page for your publication, use a separate domain or use the blog posting function.

**Pull request merged**
